### ISSUE TITLE
output的适配问题咨询

### ISSUE THREAD

**Issue by fxyouruo** [Hunterhuan/sphereface2_speaker_verification#1]
您好，非常高兴看到开源了这部分代码。我看到该代码和wespeaker的结构是一致的，但是在使用的过程中，对SphereFace2的output和loss不太理解：output的计算没有使用margin_type='A'或者margin_type=‘C’的任何一项，loss的输出维度是不满足wespeaker的要求的。我想咨询一下，这部分如何merge到wespeaker上，需要怎么修改比较合适呢？
非常感谢您的的工作，期待回复！

**Comment by Hunterhuan** [comment]
SphereFace2 has been supported in Wespeaker toolkit, see [#173](https://github.com/wenet-e2e/wespeaker/pull/173).

Thanks~

**Comment by fxyouruo** [comment]
> SphereFace2 has been supported in Wespeaker toolkit, see [#173](https://github.com/wenet-e2e/wespeaker/pull/173).
> 
> Thanks~

明白了，非常感谢！
