### ISSUE TITLE
Paper "Self-Supervised Speaker Verification Using Dynamic Loss-Gate and Label Correction"

### ISSUE THREAD

**Issue by gancx** [Hunterhuan/sphereface2_speaker_verification#2]
Thanks for your impressive work. I recently read your conference paper "Self-Supervised Speaker Verification Using Dynamic Loss-Gate and Label Correction." I wonder if you are going to or willing to release the code for model training. Thank you.

**Comment by Hunterhuan** [comment]
> Thanks for your impressive work. I recently read your conference paper "Self-Supervised Speaker Verification Using Dynamic Loss-Gate and Label Correction." I wonder if you are going to or willing to release the code for model training. Thank you.

The code will not be released temporarily. But it's not difficult for you to reproduce based on current open source code replication.

The algorithm can be divided into two stages:

stage I is DINO, we have released the DINO code in WeSpeaker https://github.com/wenet-e2e/wespeaker/tree/master/examples/voxceleb/v3. And this code can achieve better performance comparing with the system in our paper.

Stage II is using pseudo label to train the model iteratively. This process can also be reproduced based on Wespeaker https://github.com/wenet-e2e/wespeaker/tree/master/examples/voxceleb/v2

Note that the cluster algorithm is supported by faiss library.

If you have any question, please feel free to contact me.

**Comment by gancx** [comment]
> > Thanks for your impressive work. I recently read your conference paper "Self-Supervised Speaker Verification Using Dynamic Loss-Gate and Label Correction." I wonder if you are going to or willing to release the code for model training. Thank you.
> 
> The code will not be released temporarily. But it's not difficult for you to reproduce based on current open source code replication.
> 
> The algorithm can be divided into two stages:
> 
> stage I is DINO, we have released the DINO code in WeSpeaker https://github.com/wenet-e2e/wespeaker/tree/master/examples/voxceleb/v3. And this code can achieve better performance comparing with the system in our paper.
> 
> Stage II is using pseudo label to train the model iteratively. This process can also be reproduced based on Wespeaker https://github.com/wenet-e2e/wespeaker/tree/master/examples/voxceleb/v2
> 
> Note that the cluster algorithm is supported by faiss library.
> 
> If you have any question, please feel free to contact me.

Thanks for your reply. I will try your toolkit first.
