### ISSUE TITLE
Inquiry about the universal confidence threshold b

### ISSUE THREAD

**Issue by JuseokSeong** [Hunterhuan/sphereface2_speaker_verification#3]
Thank you for the nice work!

I wonder if it is possible to use the universal confidence threshold b proposed in SphereFace2 as an actual threshold?

We set -b/s as the threshold and compared it with the similarity score.  However, it does not yield good performance.
The following code explains the method I described.
fun_g(cos, self.t) > -self.bias[0][0] / self.scale -> Samples predicted as positive
fun_g(cos, self.t) < -self.bias[0][0] / self.scale -> Samples predicted as negative
(name of these variables is same in https://github.com/Hunterhuan/sphereface2_speaker_verification/blob/main/projections.py)

If there are any related codes or methods, please let me know.
Thank you.

**Comment by Hunterhuan** [comment]
Discussed in another issue:
https://github.com/wenet-e2e/wespeaker/issues/374
